### ISSUE TITLE
[QUESTION] "invalid value for folder (must be a valid folder id)" when trying to run terraform apply command

### ISSUE THREAD

**Issue by Vincsz** [aws-observability/terraform-aws-observability-accelerator#147]
Hi all,

I'm trying to setup the Observability Accelerator stack, but I'm facing an issue when I run the "terraform apply" command :

![image](https://user-images.githubusercontent.com/49070167/230383446-4b212069-9d32-46aa-8ed6-299711927061.png)

I don't know how to fix the issue, the variable doesn't seem to come from my side of the configuration.
Can someone help ?

Thanks,
Vincent

**Comment by vchintal** [comment]
A recent change has gone thru in which if you look closely at the `variables.tf` file `create_dashboard_folder` and `enable_dashboards` values at any given point must be both either `true` or both set to `false`. Since the default values for `create_dashboard_folder` is `false` and the default value of `enable_dashboards` is set to true, there is a mismatch and hence a bug.  As a temporary workaround, instead of variables assuming default values,  please explicitly set the variables in your terraform files but to the same boolean value which in your case is `true`.

**Comment by vchintal** [comment]
A recent change has gone thru in which if you look closely at the variables.tf file default values for `create_dashboard_folder` is `false` and the default value of `enable_dashboards` is set to `true` and  hence the terraform is trying to publish dashboard files to a folder when one isn't there (or created). So as a temporary workaround please explicitly set the  variable `create_dashboard_folder` to `true` if and only if you want to enable dashboards as well. We will issue a fix soon for such scenarios.

**Comment by bonclay7** [comment]
Should be resolved by #148. Thanks for raising @Vincsz

**Comment by Vincsz** [comment]
Thanks for your quick help ! 👍
