### ISSUE TITLE
API server metrics scrape scope

### ISSUE THREAD

**Issue by bonclay7** [aws-observability/terraform-aws-observability-accelerator#209]
so here maybe we should see what metrics we are not using and discard them from ingestion. I'm worried about what could be the impact at scale of non-used metrics being ingested into AMP

_Originally posted by @bonclay7 in https://github.com/aws-observability/terraform-aws-observability-accelerator/pull/208#discussion_r1287625702_

**Comment by youwalther65** [comment]
Valid point. Because many of the metrics are in Alpha stage and undergoing renaming frequently, the best approach would be dropping metrics not needed in the current API server related dashboards instead of filtering for used metrics. In addition regex filtering for metrics might be more expensive for OTEL collector.
