### ISSUE TITLE
Existing cluster with existing external-secrets addon

### ISSUE THREAD

**Issue by rohits123** [aws-observability/terraform-aws-observability-accelerator#256]
#### Please describe your question here
Is it possible to use eks_cluster_monitoring module for an existing cluster with existing external-secrets addon. 
Looking at code it will save secrets like grafana_api_key only if enable_external_secrets is true. But it fails if external-secrets addon already exists in the cluster.

**Comment by hmkmartini** [comment]
I am also interested in this particular case. The only way that I found out to run the observability accelerator terraform when external secrets are already deployed is:
1. set `enable_external_secrets` to `false`
2. set `enable_dashboards` to `false`, which depends on the external secrets
3. set `enable_fluxcd` to `false`, which also depends on the external secrets

Is there a better way to achieve this? I don´t mind disabling fluxcd since I'm using argocd. But I would like to keep the dashboards deployment.
